name: Run fetch.py and deploy frontend

on:
  push:
    branches: [ main ]
  schedule:
    - cron: 0 * * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Python
        uses: actions/setup-python@v5.3.0
        with:
          cache: pip          

      - name: Install Requirements
        run: pip install -r ./requirements.txt

      - name: Fetch
        run: python ./fetch.py

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0
        with:
          cache: npm          

      - name: Install Packages
        run: npm install

      - name: Build
        run: npm run build

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: ./dist                

  deploy:
    needs: build
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-24.04
    steps:
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v4.0.5
        id: deployment
