name: Run fetch.py and deploy frontend

on:
  push:
    branches: [ main ]
  schedule:
    - cron: 0 1,13 * * *
  workflow_dispatch:

jobs:
  fetch-and-deploy:
    name: Fetch and Deploy
    runs-on: ubuntu-24.04
    timeout-minutes: 30

    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Python
        uses: actions/setup-python@v5.3.0
        with:
          cache: pip          

      - name: Install Requirements
        run: pip install -r ./requirements.txt

      - name: Fetch
        run: python ./fetch.py

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.1.0
        with:
          cache: npm          

      - name: Install Packages
        run: npm install

      - name: Build
        run: npm run build

      - name: Push to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/dist
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
