name: Run fetch.py and deploy frontend

on:
  push:
    branches: [ main ]
  schedule:
    - cron: 0 1,13 * * *
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Git checkout
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Python task
        uses: actions/setup-python@v5.3.0
        with:
          cache: pip          
        run: pip install -r ./requirements.txt
        run: python ./fetch.py

      - name: Node.js task
        uses: actions/setup-node@v4.1.0
        with:
          cache: npm          
        run: npm install
        run: npm run build
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: ./dist                

  deploy:
    needs: build
    permissions:
      id-token: write
      pages: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-24.04
    steps:
      - name: Deploy GitHub Pages site
        uses: actions/deploy-pages@v4.0.5
        id: deployment
